### ISSUE TITLE
'#' is replaced with '||' in episode.csv

### ISSUE THREAD

**Issue by NotaninDev** [TerryCavanagh/diceymodgeons#25]
When I save the mod, all '#' in code like "before start turn" in episode.csv are replaced with '||'. The game can load the mod, but when a fight starts, it crashes.

**Comment by mrcdk** [comment]
Where are you using `#`?

This is part of how the game loads and sanitizes the scripts (there are some characters that are needed for scripts but will mess up the csv file) `#` is used substituting `||` in the final script so you can do `if(something || another) {}` which in the csv it will be `if(something # another) {}`

The mod editor converts those characters to the real ones so it's easier for us to write code.

I'll close this issue because I can't really do much from here.

Thanks for the report!

**Comment by NotaninDev** [comment]
No, that's not what I mean. I'm using `#` as logical OR, of course.

I have lots of `#` in my episode.csv, something like `if (extraspace > 1 # extraspace == 1 && eqsize == ~small~) { dowhatever(); }`. When I loaded my mod using Modgeons and saved, all `#` were replaced with `||`. They are displayed as `||` even in Excel.

**Comment by mrcdk** [comment]
oh! okay I see. Thanks for clarifying that 😅

**Comment by mrcdk** [comment]
okay, fixed. Thanks!
